apiVersion: v1
kind: Secret
metadata:
  name: licitaciones-secret
  namespace: licitaciones
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change_this_password"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=licitaciones;Username=licitaciones_app;Password=change_this_password"